# Generated by Django 4.2.29 on 2026-03-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_alter_hubconfig_hub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitatZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sensors', models.JSONField(default=list)),
                ('thresholds', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'habitat_zone',
            },
        ),
    ]
