# Generated by Django 4.2.30 on 2026-06-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_habitatzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('difficulty', models.CharField(default='off', max_length=32)),
                ('crew_size', models.IntegerField(default=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('sols_survived', models.IntegerField(default=0)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'survival_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SurvivalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField(default=0)),
                ('reasoning', models.TextField()),
                ('actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='sensor_data.survivalrun')),
            ],
            options={
                'db_table': 'survival_decision',
                'ordering': ['sol', 'id'],
                'indexes': [models.Index(fields=['run', 'sol'], name='survival_de_run_id_6feaa7_idx')],
            },
        ),
    ]
