# Generated by Django 4.2.30 on 2026-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0004_survivalrun_survivaldecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('sol', models.IntegerField(default=0)),
                ('farm_layout', models.JSONField(blank=True, null=True)),
                ('food_plan', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'survival_plan',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
