# Generated by Django 4.2.30 on 2026-06-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0005_survivalplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichedsensordata',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='enrichedsensordata',
            name='hub_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
